---
- hosts: all
  become: yes
  vars:
  # where to install jboss
  - jboss_path: /usr/share

  # jboss linux user and group
  - jboss_user: jboss
  - jboss_group: jboss
  - jboss_version: jboss-eap-6.4
  - jboss_file: jboss-eap-6.4.0.zip

  # jboss eap administrator user and password
  - jboss_admin_user: jboss
  - jboss_admin_password: jboss!123

  # MySQL configuration
  - DB_USER: ticket
  - DB_PASSWORD: Test!123
  - DB_HOST: localhost
  - DB_PORT: 3306
  - DB_NAME: ticketmonster


  tasks:
  - name: Install Java 1.8 and dependencies
    yum: name={{item}} state=present
    with_items:
      - unzip
      - java-1.8.0-openjdk
      - libselinux-python
      - libsemanage-python

  - name: Extract JBoss EAP archive
    unarchive: src=install/{{jboss_file}} dest={{jboss_path}} copy=yes
    notify:
      - create jboss_admin

  - name: Add group "{{jboss_group}}"
    group: name={{jboss_group}}

  - name: Add user "{{jboss_user}}"
    user: name={{jboss_user}} group={{jboss_group}} home={{jboss_path}}/{{jboss_version}}

  - name: Apply JBoss Configuration
    copy: src=configuration/standalone.conf dest="{{jboss_path}}/{{jboss_version}}/bin/standalone.conf"

  - name: Deploy modules
    copy: src=modules/  dest="{{jboss_path}}/{{jboss_version}}/modules"

  - name: MySQL connection configuration
    template: src=templates/standalone.j2 dest="{{jboss_path}}/{{jboss_version}}/standalone/configuration/standalone.xml"

  - name: Change ownership of JBoss installation
    file: path="{{jboss_path}}/{{jboss_version}}" owner={{jboss_user}} group={{jboss_group}} state=directory recurse=yes

  - name: Deploy application
    copy: src=deployments/ticket-monster.war dest="{{jboss_path}}/{{jboss_version}}/standalone/deployments/"

  handlers:
  - name: create jboss_admin
    shell: "{{jboss_path}}/{{jboss_version}}/bin/add-user.sh -u '{{jboss_admin_user}}' -p '{{jboss_admin_password}}'"
